import LocalizedStrings from "react-native-localization";
import { Platform } from "react-native";
export default (strings = new LocalizedStrings({
  it: {
    title_home: "Home",
    phone_number: "NUMERO DI TELEFONO",
    password: "PASSWORD",
    login: "LOGIN",
    Logout: "Logout",
    not_have_account: "Non hai ancora un account?",
    registration: "REGISTRATI",
    please_wait: "Si prega di attendere...",
    password_reset: "RESET PASSWORD",
    Occupation: "Occupation",
    reg_name: "NOME",
    profile_updated:"Profilo aggiornato",
    processing_request:"Stiamo processando la richiesta.",
    you_will_sms_token:
      "Riceverai un SMS con un codice. Inserisci il codice per ricevere la tua nuova password",
    passwor_reset_send: "Attenzione !! Nuova password inviata via SMS",
    resetToken: "Token ",
    Do_you_have_token_enter_token:
      "Inserire il codice  ricevuto precedentemente ",
    or: "OPPURE",
    request_new_token:
      "Inserisci il numero di telefono per ricevere un nuovo token",
    new_password_sent:
      "Attenzione Ti abbiamo mandato un SMS con il nuovo codice",
    reg_surname: "COGNOME",
    reg_email: "EMAIL",
    req_phone_number: "TELEFONO",
    reg_dob: "DATA DI NASCITA",
    reg_occupation: "CHE LAVORO FAI?",
    reg_man: "campi obbligatori",
    reg_cnf_password: "CONFERMA PASSWORD",
    alert:"Attenzione",
    login_failed:" Credenziali non valide ",
    login_check_box_one:
      "Autorizzo il trattamento dei miei dati personali. Leggi i termini di ",
    login_check_box_one_underline: "Privacy e Policy",
    login_check_box_two:
      "Autorizzo il trattamento dei miei dati personali a scopo di terzi.",
    login_check_box_three:
      "Autorizzo il trattamento dei miei dati personali per fini di marketing.",
    login_check_box_four: "Ho letto e accetto i termini contrattuali.Leggi i ",
    login_check_box_four_underline: "termini e le condizioni",

    home_latest_product_purchased: "ULTIMI PRODOTTI ACQUISTATI",
    home_search: "Cerca un prodotto",
    home_btn: "TI SERVE AIUTO?",
    preference: "preferiti",
    no_favorites: "Non ci sono favoriti",
    CATALOG: "CATALOGO",
    Noproducts: "Non sono stati trovati prodotti",
    ProductLoading: "Caricamento prodotti",
    //profile
    details: "DET",
    dob: "Data di nascita",
    gender: "Gender",
    female: "Donna",
    male: "uomo",
    ph_no: "Numero di telefono",
    email: "Email",

    pw: "Password",
    fiscal_code: "Codice Fiscale",
    piva: "P.IVA",
    telematic_address: "INDIRIZZO TELEMATICO",
    Telematic_address: "Indirizzo telematico",
    primary_address: "Indirizzo principale",
    privacy_policy: "PRIVACY E POLICY",
    DETAILS: "DETTAGLI",
    // wallet
    wallet_title: "WALLET",
    wallet_balance: "IL TUO SALDO E’",
    wallet_credit: "crediti",
    wallet_credit_recharge: "Il tuo credito si ricaricherà il",
    // cart
    cart_title: "CARRELLO",
    Delete: "Togli",
    cart_total: "TOTALE (iva e costi di spedizione inclusi)",
    cart_check_out: "CHECK OUT",
    confirm_pay: "CONFERMA PAGAMENTO",
    no_product_cart: "Nessun articolo presente",
    loading_cart: "Caricamento carrello..",
    Product_added: "Prodotto aggiunto al carrello",
    //address
    shipment: "SPEDIZIONE",
    payment: "PAGAMENTO",
    Payment: "Pagamento",
    report: "RESOCONTO",
    delivery_address: "Indirizzo di consegna",
    dropLocations: "Drop Locations",
    time_slot_address: "Fascia Oraria",
    failSlot:
      "Non è stato possibile allocare la fascia oraria. Torna al carrello per ricominciare.",
    Invalid_Order: "Il tuo ordine non esiste",
    Try_again: "Riprova",
    add_address: "Aggiungi indirizzo",
    add_newAddress: "Salva indirizzo",
    new_address_added:"indirizzo aggiunto",
    address_updated:"Indirizzo aggiornato",
    ADDRESS: "INDIRIZZI",
    //payment
    payment_method: "METODO DI PAGAMENTO",
    need_invoice: "Richiedo emissione della fattura",
    no_payment_methods: "Nessun metodo di pagamento",
    loading_payment: "Loading Payment Methods.",
    payment_bank_failed: "Attenzione. Pagamento annullato",
    orders: "Storico Ordini",
    CREDITS: "CREDITI",
    fail_payList: "Errore nel caricamento dei metodi di pagamento",
    failPayment: "Non è stato possibile processare il pagamento",
    failWalltetPay: "Non è stato possibile pagare con il Wallet",
    payment_process: "Pagamento in corso",
    set_partiva: "Devi prima inserire la tua Partita IVA nel profilo",
    successPayment: "Pagamento processato correttamente.",
    reviewPayment: "Non è stato possibile processare il pagamento",
    product_details_add: "AGGIUNGI",
    process_payment: "Pagamento in corso",
    thankyou_waiting: "Grazie per l'attesa",
    product_details_description: "DESCRIZIONE",
    order_details_time_slot: "FASCIA ORARIA",
    order_details_payment_method: "METODO DI PAGAMENTO",

    //payment success
    payment_recieved: "Il tuo pagamento è stato processato correttamente",
    review_orders: "Controlla i tuoi ordini dal menu ",
    take_me_home: "Home",
    //order history
    ORDERS_HISTORY: "STORICO ORDINI",
    no_orders_yet:"Non sono ancora presenti ordini",
    DELIVERY_ADD: "INDIRIZZO DI CONSEGNA",
    TIMESLOT: "FASCIA ORARIA",
    summary: "RIEPILOGO",
    PAYMENT_METHOD: "METODO DI PAGAMENTO",
    PRODUCTS: "PRODOTTI",
    ORDERNUM: "ORDINE N°",
    Delivered_to_customer: "Consegnato al cliente",
    CONFIRMED: "CONFERMATO",
    IN_TRANSIT: "IN TRANSITO",
    DELIVERED: "CONSEGNATO",

    //orders
    fetching_orders: "Caricamento ordini",
    //user profile
    SDD_method: "Metodo di pagamento collegato SDD",
    active_state: "STATO ATTIVO",
    PROFILE: "PROFILO",
    My_details: "I tuoi dettagli",
    Password_change: "Cambia Password",
    Confirm_password: "Conferma Password",
    Password: "Password",
    password_updated: "Password modificata",
    fill_both_password:
      "Riempire entrambi i campi Password e Conferma Password",
    pass_mismatch: "Le Passwords non coincidono",
    Update_password: "Modifica Password",
    Update_profile: "Modifica Profilo",
    Address: "Indirizzi",
    order_history: "Storico ordini",
    price: "Prezzo",
    price_for: "Prezzo al",
    //settings
    SETTINGS: "IMPOSTAZIONI",
    setting_tutorials: "NOTIFICHE E TUTORIAL",
    do_you_want_notification:
      "Vuoi ricere le notifiche sulla scadenza dei prodotti da te acquistati?",
    notif_tutorial: "Notifiche e Tutorial",
    Privacy_Policy: "Privacy Policy",
    notification_state: "NOTIFICHE ATTIVE",
    view_toturials:
      "Visualizza il tutorial per imparare a utlizzare l’app di Prontolo",
    //Address Form
    Province: "Provincia",
    State: "Stato",
    alter_address: "Altri indirizzi",
    field_required: " è obbligatorio",
    Error: "Error !!",
    Processing: "In elaborazione...",
    was_removed: " é stato rimosso.",
    Searchingfor: "Ricerca in corso ",
    Updating: "Aggiornamento in corso…",
    minimum_char: " caratteri minimi richiesti",
    invalid: " Invalida ",
    text_logout_title: "Sessione Invalida",
    text_logout_confirm: "Effettua nuovamente la login",
    Registration_Success: "Registrazione effettuata con successo",
    Address_new_Success: "Nuovo indirizzo aggiunto",
    address_deletd: "Indirizzo cancellato",
    Address_Update_Success: "Indirizzo modificato",

    // font
    ...Platform.select({
      ios: {
        lBold: "Lato-Bold",
        lLight: "Lato-Light",
        lMedium: "Lato-Medium",
        lRegular: "Lato-Regular",
        lSemiBold: "Lato-Semibold"
      },
      android: {
        lBold: "lato_bold",
        lLight: "lato_light",
        lMedium: "lato_medium",
        lRegular: "lato_regular",
        lSemiBold: "lato_semibold"
      }
    })
  }
}));
