# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Prontolo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Prontolo

    pod 'Firebase'
    pod 'Firebase/Messaging'


    pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

    target 'ProntoloTests' do
    inherit! :search_paths
    # Pods for testing
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTLinkingIOS',
    'CxxBridge'
  ]

  end

end

